### ISSUE TITLE
Support for Rust?

### ISSUE THREAD

**Issue by Boscop** [Doctave/dossier#12]
It would be great if dossier could support Rust. Any plans for that? :)

**Comment by begleynk** [comment]
Mentioned in the other issue that we're no longer really maintaining Dossier, but wanted to comment that Rust is a particularly tricky language to parse in this way.

But because Dossier itself is written in Rust, perhaps there's a way to cheat somehow and use the Rust compile itself to do the heavy lifting?

Another option is using Rustdoc's JSON output (currently still unstable): https://rust-lang.github.io/rfcs/2963-rustdoc-json.html

That would essentially give you the same information that Dossier would give you, assuming we had support for Rust. I'd recommend exploring that path.

**Comment by Boscop** [comment]
Thanks!
